{% set version = "1.15.0" %}

package:
  name: libfido2
  version: {{ version }}

source:
  url: https://github.com/Yubico/libfido2/archive/{{ version }}.tar.gz
  sha256: 32e3e431cfe29b45f497300fdb7076971cb77fc584fcfa80084d823a6ed94fbb

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libfido2', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - openssl
    - libcbor
    - libudev  # [linux]
    - zlib

test:
  commands:
    - test -f "${PREFIX}/lib/libfido2${SHLIB_EXT}"

about:
  home: https://github.com/Yubico/libfido2/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Provides library functionality for FIDO 2.0

extra:
  recipe-maintainers:
    - chrisburr
