build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_forge_output_validation: true
os_version:
  linux_64: cos7
provider:
  linux_aarch64: default
  linux_ppc64le: default
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
bot:
  automerge: true
test: native_and_emulated
